prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        team: devops
    ruleSelector:
      matchLabels:
        release: prometheus

alertmanager:
  enabled: true

grafana:
  enabled: false
